---
title: Remove Win32 apps
description: Removal of Win32 apps
privilege: TrustedInstaller
actions:

  # Microsoft Edge
  - !writeStatus: {status: "Removing MS Edge"}
  - !taskKill: {name: "MicrosoftEdgeUpdate", errorAction: Ignore}
  - !taskKill: {name: "msedge", errorAction: Ignore}
  - !taskKill: {name: "MicrosoftEdge*", errorAction: Ignore}
  - !taskKill: {name: "setup", errorAction: Ignore, pathContains: "\\Edge"}

  # Setting device region to US (244) allows uninstallation without known parent processes

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Control Panel\DeviceRegion', value: 'DeviceRegion', type: REG_DWORD, data: '244', iso: only}
  - !registryValue: {path: 'HKU\.DEFAULT\Control Panel\International\Geo', value: 'Nation', type: REG_SZ, data: '244', iso: only}

  - !powerShell:
    command: '.\Scripts\EDGE.ps1 -Mode SetDeviceRegion -DeviceRegion 244'
    exeDir: true

  - !powerShell:
    command: '.\Scripts\EDGE.ps1 -Mode EdgeBrowser'
    exeDir: true
    runas: currentUserElevated
    weight: 40

  - !powerShell:
    command: '.\Scripts\EDGE.ps1 -Mode RestoreDeviceRegion'
    exeDir: true

  - !powerShell:
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\Scripts\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.MicrosoftEdge',
        'Microsoft.MicrosoftEdgeDevToolsClient',
        'Microsoft.Edge.GameAssist'
      )

  # In case Revision Tool's removal method fails
  - !powerShell:
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\Scripts\APPX-REMOVER.ps1 -Packages 'Microsoft.Copilot'

  # OneDrive
  - !writeStatus: {status: "Removing OneDrive"}
  - !taskKill: {name: "OneDriveStandaloneUpdater", errorAction: Ignore}
  - !taskKill: {name: "OneDriveSetup", errorAction: Ignore}
  - !taskKill: {name: "OneDrive*", errorAction: Ignore}

  - !run: {exeDir: true, exe: 'batch_files\ONED.cmd', oobe: false, iso: false, weight: 40}
  - !file: {path: "%SystemDrive%\\OneDriveTemp"}
  - !file: {path: "%ProgramData%\\Microsoft OneDrive"}

  - !powerShell:
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\Scripts\APPX-REMOVER.ps1 -Packages @(
        'OneDrive',
        'microsoft.microsoftskydrive'
      )

  # Teams
  - !writeStatus: {status: "Removing Teams"}
  - !taskKill: {name: "Teams", errorAction: Ignore}
  - !taskKill: {name: "Update", errorAction: Ignore}
  - !taskKill: {name: "ms-teamsupdate", errorAction: Ignore}

  - !powerShell:
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\Scripts\APPX-REMOVER.ps1 -Packages @(
        'MicrosoftTeams',
        'MSTeams', # New Teams
        'Flipgrid'
      )

  # Microsoft Teams Meeting Add-in for Microsoft Office
  - !run:
    wait: true
    exe: 'msiexec.exe'
    args: "/qn /norestart /X{A7AB73A3-CB10-4AA5-9D38-6AEFFBDE4C91}"
    weight: 10
    showError: false
    runas: currentUserElevated

  # === Prevent automatic Teams installation
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Communications', value: 'ConfigureChatAutoInstall', type: REG_DWORD, data: '0'}